import { combineReducers } from 'redux';
import BooksReducer from './reducer_books'
/*
## CORE CONCEPT
// Application State - Generated by Reducers
{
  books:[{title:'Harry Potter'},{title:'Javascript'}], // Books reducer
  activeBook:{title:'Javascript'} // Active Book reducer
}

*/
const rootReducer = combineReducers({
  //state: (state = {}) => state
  // This is a mapping of the state
  books:BooksReducer
});

export default rootReducer;
